// Zygote management messages

table Ack {}

table Exit {}

table IdentityQuery {}

table IdentityQueryResponse {
    name: string (required);
    species: string (required);
    arch: string (required);
}

table SpawnAndroidNative {
    package: string (required);
}

table SpawnMock {
    name: string (required);
}

table SpawnLibApp {
    path: string (required);
    args: [string] (required);
}

union SpawnPayload {
    SpawnAndroidNative,
    SpawnLibApp,
    SpawnMock,
}

table Spawn {
    uid: int32;
    gid: int32;

    payload: SpawnPayload (required);
}

table SpawnResponse {
    pid: int32;
}

table Stat {}

union Message {
    Ack,
    Exit,
    IdentityQuery,
    IdentityQueryResponse,
    Spawn,
    SpawnResponse,
    Stat,
}

table Parcel {
    message: Message;
}

root_type Parcel;