// Helper types

struct RLimitData {
    resource: uint32;
    hard: uint64;
    soft: uint64;
}

// Zygote management messages

table Ack {}

table Exit {}

table IdentityQuery {}

table IdentityQueryResponse {
    name: string (required);
    species: string (required);
    arch: string (required);
}

table SpawnAndroidNative {
    package: string (required);
    start_seq: int64;
}

table SpawnMock {
    name: string (required);
}

table SpawnLibApp {
    path: string (required);
    args: [string] (required);
}

union SpawnPayload {
    SpawnAndroidNative,
    SpawnLibApp,
    SpawnMock,
}

table Spawn {
    uid: int32;
    gid: int32;

    priority_initial: int32;
    priority_final: int32;

    cap_effective: uint64;
    cap_permitted: uint64;
    cap_inheritable: uint64;
    cap_bound: uint64;

    secondary_groups: [uint32];
    rlimits: [RLimitData] (required);

    payload: SpawnPayload (required);
}

table SpawnResponse {
    pid: int32;
}

table Stat {}

table StatResponse {
    pid: uint32;
    pgrp: uint32;
    minflt: uint64;
    cminflt: uint64;
    majflt: uint64;
    cmajflt: uint64;
    utime: uint64;
    stime: uint64;
    num_threads: uint64;
    vsize: uint64;
    rss: uint64;
}

union Message {
    Ack,
    Exit,
    IdentityQuery,
    IdentityQueryResponse,
    Spawn,
    SpawnResponse,
    Stat,
    StatResponse,
}

table Parcel {
    message: Message;
}

root_type Parcel;
