[package]
name = "zygote-messages"
version = "0.1.0"
edition = "2024"

[features]
default = ["libapp"]
android-native = []
libapp = []
mock = []
test = ["mock"]

[dependencies]
anyhow = "1.0.97"
arrayvec = "0.7.6"
bitflags = "2.9.4"
cap = { path = "../../librustutils/cap/" }
clap = { version = "4.5.0", features = ["derive"] }
flatbuffers = "25.1.24"
itertools = "0.14.0"
zygote-sys = { path = "../zygote-sys" }
zygote_proc_macros = { path = "../zygote-proc-macros" }

[build-dependencies]
which = "7.0.3"
