// Helper types

struct RLimitData {
    resource: uint32;
    hard: uint64;
    soft: uint64;
}

// Zygote management messages

table Ack {}

table Exit {}

table IdentityQuery {}

table IdentityQueryResponse {
    name: string (required);
    species: string (required);
    arch: string (required);
}

table SpawnAndroidNative {
    package: string (required);
    start_seq: int64;
    target_sdk_version: int32;
    runtime_flags: uint32;
}

table SpawnSubspeciesAndroidNative {
    target_sdk_version: int32;
    runtime_flags: uint32;
    library_path: string (required);
    library_dirs: string (required);
    permitted_library_paths: string (required);
    shared: bool;
    zip_path: string (required);
    native_shared_lib_path: string (required);
    preload_func: string;
    uid_gid_min: uint32;
    uid_gid_max: uint32;
}

table SpawnMock {
    name: string (required);
}

table SpawnLibApp {
    path: string (required);
    args: [string] (required);
}

union SpawnPayload {
    SpawnAndroidNative,
    SpawnSubspeciesAndroidNative,
    SpawnLibApp,
    SpawnMock,
}

table SpawnCommon {
    uid: int32;
    gid: int32;

    process_name: string;

    priority_initial: int32;
    priority_final: int32;

    cap_effective: uint64;
    cap_permitted: uint64;
    cap_inheritable: uint64;
    cap_bound: uint64;

    se_info: string;

    secondary_groups: [uint32];
    rlimits: [RLimitData] (required);
}

table Spawn {
    common: SpawnCommon;

    payload: SpawnPayload (required);
}

table SpawnSubspecies {
    common: SpawnCommon;

    socket_path: string (required);

    payload: SpawnPayload (required);
}

table SpawnResponse {
    pid: int32;
}

table Stat {}

table StatResponse {
    pid: uint32;
    pgrp: uint32;
    minflt: uint64;
    cminflt: uint64;
    majflt: uint64;
    cmajflt: uint64;
    utime: uint64;
    stime: uint64;
    num_threads: uint64;
    vsize: uint64;
    rss: uint64;
}

union Message {
    Ack,
    Exit,
    IdentityQuery,
    IdentityQueryResponse,
    Spawn,
    SpawnSubspecies,
    SpawnResponse,
    Stat,
    StatResponse,
}

table Parcel {
    message: Message;
}

root_type Parcel;
